version: 2
project_name: zones-operator

env:
  - DOCKER_IMAGE_REPO={{ envOrDefault "DOCKER_IMAGE_REPO" "zones-operator" }}

builds:
  - id: operator
    binary: operator
    main: main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/zeiss/zones-operator/main.version={{.Version}} -X github.com/zeiss/zones-operator/main.commit={{.Commit}} -X github.com/zeiss/zones-operator/main.date={{.Date}}

archives:
  - ids: [ operator]

dockers_v2:
  - id: operator
    dockerfile: Dockerfile
    images:
      - "{{ .Env.DOCKER_IMAGE_REPO }}"
    tags:
      - "{{ .Version }}"
      - latest
    ids:
      - operator
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"

gomod:
  proxy: false

release:
  draft: false

changelog:
  groups:
     - title: Features
       regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
       order: 0
     - title: "Bug fixes"
       regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
       order: 1
     - title: Others
       order: 999
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - typo
      - (?i)foo

snapshot:
  version_template: "{{.Tag}}"

checksum:
  name_template: "operator_checksums.txt"
