apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zones-operator.fullname" . }}-manager-role
  labels:
  {{- include "zones-operator.labels" . | nindent 4 }}
rules:
- resources:
  - events
  apiGroups:
  - ""
  - events.k8s.io
  verbs:
  - create
  - patch
  - update
- resources:
  - configmaps
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zones.zeiss.com
  resources:
  - zonesclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zones.zeiss.com
  resources:
  - zonesclusters/finalizers
  verbs:
  - update
- apiGroups:
  - zones.zeiss.com
  resources:
  - zonesclusters/status
  verbs:
  - get
  - patch
  - update
