apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zones-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zones-operator
    app.kubernetes.io/part-of: zones-operator
  {{- include "zones-operator.labels" . | nindent 4 }}
